# Generated by Django 5.0.3 on 2024-03-11 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the category.', max_length=50, verbose_name='Name')),
                ('body', models.TextField(help_text='Enter the body of your category.', verbose_name='Body')),
                ('image', models.ImageField(help_text='Image', upload_to='media/categories/%Y/%m/%d', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of your post.', max_length=255, verbose_name='Title')),
                ('body', models.TextField(help_text='Enter the body of your post.', verbose_name='Body')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the post is approved or not.', verbose_name='Approved')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='The date and time the post was created.', verbose_name='Created On')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='The date and time the post was last modified.', verbose_name='Last Modified')),
                ('image', models.ImageField(help_text='Image', upload_to='media/posts/%Y/%m/%d', verbose_name='Image')),
                ('author', models.ForeignKey(help_text='Post creator', on_delete=django.db.models.deletion.PROTECT, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ManyToManyField(help_text='Categories', to='posts.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='The date and time the comment was created.', verbose_name='Created On')),
                ('author', models.ForeignKey(help_text='Comment creator', on_delete=django.db.models.deletion.PROTECT, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment Creator')),
                ('post', models.ForeignKey(help_text='Select the post to which this comment will be associated.', on_delete=django.db.models.deletion.PROTECT, related_name='post_comments', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_likes', to='posts.post')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('author', 'post')},
            },
        ),
    ]
