# Generated by Django 4.2.11 on 2024-03-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_post_like_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of your post.', max_length=255, verbose_name='Title')),
                ('body', models.TextField(help_text='Enter the body of your post.', verbose_name='Body')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='The date and time the post was created.', verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_on',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Post creator', on_delete=django.db.models.deletion.PROTECT, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Image', null=True, upload_to='media/posts/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categories', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_posts', to='posts.category', verbose_name='Categories'),
        ),
    ]
