# Generated by Django 4.2.11 on 2024-03-16 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_notification_alter_post_author_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='8d759607-2312-4273-b4af-2d777210c24d', help_text='Categories', on_delete=django.db.models.deletion.PROTECT, related_name='category_posts', to='posts.category', verbose_name='Categories'),
            preserve_default=False,
        ),
    ]
