# Generated by Django 4.2.11 on 2024-03-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(help_text='Enter the body of your post.', max_length=150, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Enter the title of your post.', max_length=50, verbose_name='Title'),
        ),
    ]
