# Generated by Django 4.2.11 on 2024-03-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='Select the post to which this comment will be associated.', on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.post', verbose_name='Post'),
        ),
    ]
